[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sql_metadabs"
dynamic = [
    "dependencies",
    "version",
]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
